### ISSUE TITLE
RaceRoom telemetry

### ISSUE THREAD

**Issue by paoloambrosio** [OpenSimTools/RaceDirector#48]
Expose all fields required by Sector3 Studios [WebHud](https://github.com/sector3studios/webhud) in the same way as the official `Dash.exe` does.

 - [x] Read telemetry and transform it to standardise format
   - [x] Error if Major version doesn't match
 - [x] Expose it back on the WebSocket
    - [ ] It should run the WebHud (#6, #34)
    - [ ] It should run OtterHud (#47)
 - [ ] Support all gaming modes
   - [x] Menu
   - [x] Race (SP, MP)
   - [ ] Practice
   - [ ] Leaderboard
   - [ ] Replay (during race or standalone)
   - [ ] Spectator
   - [ ] Between sessions
 - [ ] Update documentation
