### ISSUE TITLE
ACC telemetry

### ISSUE THREAD

**Issue by paoloambrosio** [OpenSimTools/RaceDirector#49]
Implement telemetry for ACC with what provided by memory-mapped files and UDP socket.

 - [ ] Read MM telemetry
   - [x] Error if Major version doesn't match
   - [x] Handle absence of MM files
   - [x] Handle reading from 3 files independently
   - [ ] Cool off period before trying to open the file again (e.g.  from 15ms to 1s poll time - simulated by skipping reads)
 - [ ] Receive UDP telemetry (requires #28 or it would be a lot of work for nothing)
   - [ ] Ignore UDP telemetry data if older than the current session
   - [ ] Handle reconnections if socket can't be opened or if it closes
 - [ ] Use the current MM data and the latest received UDP data
 - [ ] Support all gaming modes
   - [ ] Menu
   - [ ] Race (SP, MP driving, MP connected)
   - [ ] Practice
   - [ ] Replay (during race or standalone)
   - [ ] Spectator
   - [ ] Between sessions

Notes:
 - [Official MM documentation](https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/).
 - UDP SDK can be found on the Dedicated Server installation folder under `sdk\broadcasting`.
 - MM has no track length, the position of only 60 cars and the number of cars stops at 60. UDP has track length and all cars but no position. Some data is not anywhere like the sector length, and will have to be calculated. It's really terrible 🤦🏻‍♂️
 - Crew Chief [code](https://gitlab.com/mr_belowski/CrewChiefV4/-/tree/master/CrewChiefV4/ACC).
 - Second Monitor [code](https://gitlab.com/winzarten/SecondMonitor/-/tree/master/Connectors/AccConnector).

**Comment by paoloambrosio** [comment]
| RD | ACC UDP | ACC MM |
|--|--|--|
| GameState |  |  |
| UsingVR |  |  |
| Event.Track.SectorsEnd |  |  |
| Event.FuelRate |  |  |
| Session.Type |  |  |
| Session.Phase |  |  |
| Session.Length |  |  |
| Session.Requirements.MandatoryPitStops |  |  |
| Session.Requirements.MandatoryPitRequirements |  |  |
| Session.Requirements.PitWindow |  |  |
| Session.PitSpeedLimit |  |  |
| Session.PitLaneOpen |  |  |
| Session.ElapsedTime |  |  |
| Session.TimeRemaining |  |  |
| Session.WaitTime |  |  |
| Session.StartLights.Colour |  |  |
| Session.StartLights.Lit |  |  |
| Session.BestLap |  |  |
| Session.BestSectors.Individual |  |  |
| Session.BestSectors.Cumulative |  |  |
| Session.Flags.Track |  |  |
| Session.Flags.Sectors |  |  |
| Session.Flags.Leader |  |  |
| Vehicles[].Id |  |  |
| Vehicles[].ClassPerformanceIndex |  |  |
| Vehicles[].RacingStatus |  |  |
| Vehicles[].EngineType |  |  |
| Vehicles[].ControlType |  |  |
| Vehicles[].Position |  |  |
| Vehicles[].PositionClass |  |  |
| Vehicles[].GapAhead |  |  |
| Vehicles[].GapBehind |  |  |
| Vehicles[].CompletedLaps |  |  |
| Vehicles[].LapValid |  |  |
| Vehicles[].CurrentLapTime.Overall |  |  |
| Vehicles[].CurrentLapTime.Sectors.Individual |  |  |
| Vehicles[].CurrentLapTime.Sectors.Cumulative |  |  |
| Vehicles[].PreviousLapTime |  |  |
| Vehicles[].BestLapTime.Overall |  |  |
| Vehicles[].BestLapTime.Sectors.Individual |  |  |
| Vehicles[].BestLapTime.Sectors.Cumulative |  |  |
| Vehicles[].BestSectors |  |  |
| Vehicles[].CurrentLapDistance |  |  |
| Vehicles[].Location |  |  |
| Vehicles[].Orientation |  |  |
| Vehicles[].Speed |  |  |
| Vehicles[].CurrentDriver.Name | Partial |  |  |
| Vehicles[].Pit.StopsDone |  |  |
| Vehicles[].Pit.MandatoryStopsDone |  |  |
| Vehicles[].Pit.PitLanePhase |  |  |
| Vehicles[].Pit.PitLaneTime |  |  |
| Vehicles[].Pit.PitStallTime |  |  |
| Vehicles[].Penalties |  |  |
| Vehicles[].Flags.Green |  |  |
| Vehicles[].Flags.Blue |  |  |
| Vehicles[].Flags.Yellow |  |  |
| Vehicles[].Flags.White |  |  |
| Vehicles[].Flags.Chequered |  |  |
| Vehicles[].Flags.Black |  |  |
| Vehicles[].Flags.BlackWhite |  |  |
| FocusedVehicle.Id |  |  |
| FocusedVehicle.ClassPerformanceIndex |  |  |
| FocusedVehicle.RacingStatus |  |  |
| FocusedVehicle.EngineType |  |  |
| FocusedVehicle.ControlType |  |  |
| FocusedVehicle.Position |  |  |
| FocusedVehicle.PositionClass |  |  |
| FocusedVehicle.GapAhead |  |  |
| FocusedVehicle.GapBehind |  |  |
| FocusedVehicle.CompletedLaps |  |  |
| FocusedVehicle.LapValid |  |  |
| FocusedVehicle.CurrentLapTime.Overall |  |  |
| FocusedVehicle.CurrentLapTime.Sectors.Individual |  |  |
| FocusedVehicle.CurrentLapTime.Sectors.Cumulative |  |  |
| FocusedVehicle.PreviousLapTime |  |  |
| FocusedVehicle.BestLapTime.Overall |  |  |
| FocusedVehicle.BestLapTime.Sectors.Individual |  |  |
| FocusedVehicle.BestLapTime.Sectors.Cumulative |  |  |
| FocusedVehicle.BestSectors |  |  |
| FocusedVehicle.CurrentLapDistance |  |  |
| FocusedVehicle.Location |  |  |
| FocusedVehicle.Orientation |  |  |
| FocusedVehicle.Speed |  |  |
| FocusedVehicle.CurrentDriver.Name |  |  |
| FocusedVehicle.Pit.StopsDone |  |  |
| FocusedVehicle.Pit.MandatoryStopsDone |  |  |
| FocusedVehicle.Pit.PitLanePhase |  |  |
| FocusedVehicle.Pit.PitLaneTime |  |  |
| FocusedVehicle.Pit.PitStallTime |  |  |
| FocusedVehicle.Penalties |  |  |
| FocusedVehicle.Inputs.Throttle |  |  |
| FocusedVehicle.Inputs.Brake |  |  |
| FocusedVehicle.Inputs.Clutch |  |  |
| FocusedVehicle.Flags.Green |  |  |
| FocusedVehicle.Flags.Blue |  |  |
| FocusedVehicle.Flags.Yellow |  |  |
| FocusedVehicle.Flags.White |  |  |
| FocusedVehicle.Flags.Chequered |  |  |
| FocusedVehicle.Flags.Black |  |  |
| FocusedVehicle.Flags.BlackWhite |  |  |
| Player.RawInputs.Throttle |  |  |
| Player.RawInputs.Brake |  |  |
| Player.RawInputs.Clutch |  |  |
| Player.RawInputs.Steering |  |  |
| Player.RawInputs.SteerWheelRange |  |  |
| Player.DrivingAids.Abs |  |  |
| Player.DrivingAids.Tc |  |  |
| Player.DrivingAids.Esp |  |  |
| Player.DrivingAids.Countersteer |  |  |
| Player.DrivingAids.Cornering |  |  |
| Player.VehicleSettings.EngineMap |  |  |
| Player.VehicleSettings.EngineBrakeReduction |  |  |
| Player.VehicleDamage.AerodynamicsPercent |  |  |
| Player.VehicleDamage.EnginePercent |  |  |
| Player.VehicleDamage.SuspensionPercent |  |  |
| Player.VehicleDamage.TransmissionPercent |  |  |
| Player.Tyres[][].Dirt |  |  |
| Player.Tyres[][].Grip |  |  |
| Player.Tyres[][].Wear |  |  |
| Player.Tyres[][].Temperatures.CurrentTemperatures[][] |  |  |
| Player.Tyres[][].Temperatures.OptimalTemperature |  |  |
| Player.Tyres[][].Temperatures.ColdTemperature |  |  |
| Player.Tyres[][].Temperatures.HotTemperature |  |  |
| Player.Tyres[][].BrakeTemperatures.CurrentTemperature |  |  |
| Player.Tyres[][].BrakeTemperatures.OptimalTemperature |  |  |
| Player.Tyres[][].BrakeTemperatures.ColdTemperature |  |  |
| Player.Tyres[][].BrakeTemperatures.HotTemperature |  |  |
| Player.Fuel.Max |  |  |
| Player.Fuel.Left |  |  |
| Player.Fuel.PerLap |  |  |
| Player.Engine.Speed |  |  |
| Player.Engine.UpshiftSpeed |  |  |
| Player.Engine.MaxSpeed |  |  |
| Player.CgLocation |  |  |
| Player.Orientation |  |  |
| Player.LocalAcceleration |  |  |
| Player.ClassBestLap |  |  |
| Player.ClassBestSectors.Individual |  |  |
| Player.ClassBestSectors.Cumulative |  |  |
| Player.PersonalBestSectors.Individual |  |  |
| Player.PersonalBestSectors.Cumulative |  |  |
| Player.PersonalBestDelta |  |  |
| Player.Drs.Available |  |  |
| Player.Drs.Engaged |  |  |
| Player.Drs.ActivationsLeft.Value |  |  |
| Player.Drs.ActivationsLeft.Total |  |  |
| Player.PushToPass.Available |  |  |
| Player.PushToPass.Engaged |  |  |
| Player.PushToPass.ActivationsLeft.Value |  |  |
| Player.PushToPass.ActivationsLeft.Total |  |  |
| Player.PushToPass.EngagedTimeLeft |  |  |
| Player.PushToPass.WaitTimeLeft |  |  |
| Player.PitStop |  |  |
| Player.Warnings.IncidentPoints |  |  |
| Player.Warnings.BlueFlagWarnings |  |  |
| Player.Warnings.GiveBackPositions |  |  |
| Player.OvertakeAllowed |  |  |
